// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Netlify's provisioned Postgres sets NETLIFY_DATABASE_URL instead of
    // DATABASE_URL — fall back so `prisma migrate deploy` works there too.
    url: process.env["DATABASE_URL"] ?? process.env["NETLIFY_DATABASE_URL"],
  },
});
